GET http://localhost:8080/flowers

###
POST http://localhost:8080/flowers
Content-Type: application/json

{
  "sepalLength": 100,
  "price": 200,
  "color": "BLUE",
  "flType": "ROSE"
}

###
GET http://localhost:8080/user

###
POST http://localhost:8080/user
Content-Type: application/json

{
  "name":"Roma",
  "email": "opa.gmail",
  "dob": "2003-09-05"
}